openapi: 3.0.3
info:
  title: Bets - Players API
  version: 2.0.0
  contact:
    name: Bets
    email: bets@example.com
  license:
    name: MIT License
    url: 'https://opensource.org/licenses/MIT'
servers:
  -
    url: 'http://localhost:9999/api'
    description: Development Environment
  -
    url: 'https://bets.api.com'
    description: Production
paths:
  '/players/{player-id}':
    get:
      tags:
        - players
      parameters:
        -
          name: player-id
          description: Player ID
          schema:
            format: string
            type: string
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user-data'
              examples:
                data:
                  value:
                    name: Joe Doe
                    email: joe@doe.com
          description: 200 response
        '404':
          content:
            application/json:
              examples:
                error:
                  value:
                    code: 404
                    message: not found
          description: 404 response
      operationId: get-mesh-by-id
      summary: Get Player Details
components:
  schemas:
    user-data:
      title: Root Type for user-data
      description: ''
      type: object
      properties:
        name:
          type: string
        email:
          type: string
      example:
        name: Joe Doe
        email: joe@doe.com
tags:
  -
    name: players
    description: Everything about your Players