apiVersion: v1
kind: Service
metadata:
  name: {{ include "players.fullname" . }}
  annotations:
    konghq.com/plugins: prometheus-players
  labels:
    {{- include "players.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "players.selectorLabels" . | nindent 4 }}
