apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: players
    app.kubernetes.io/instance: players
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: players
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: players-0.1.0
    version: 1.16.0
  name: players
  namespace: bets
spec:
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: players
