apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app:  "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 10
  # Especificação do pod
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: "goserver-container"
          image: "renatofh/hello-go:v5"
          envFrom:
            - configMapRef:
                name: goserver-env
          # env:
          #   - name: NAME
          #     valueFrom:
          #       configMapKeyRef:
          #         name: goserver-env
          #         key: NAME
          #   - name: AGE
          #     valueFrom:
          #       configMapKeyRef:
          #         name: goserver-env
          #         key: AGE
