apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceName: mysql-h
  replicas: 3
  podManagementPolicy: Parallel # define a política de gerenciamento de pods para acontecer em paralelo
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.32
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
      
      
          