apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: oidc-bets
config:
  client_id: "kong"
  client_secret: "KmhQPz3IbwEdusqAGixxlRE8FDfptGu1"
  # keycloack é o nome do service
  # iam é o namespace
  # /realms é para indicar que vamos buscar um realm específico
  # bets é o nome do realm
  discovery: "http://keycloak.iam/realms/bets/.well-known/openid-configuration"
  introspection_endpoint: "http://keycloak.iam/realms/bets/protocol/openid-connect/token/introspect"
  bearer_only: "yes"
  bearer_jwt_auth_enable: "yes"
  bearer_jwt_auth_allowed_auds:
    - account
plugin: oidc
