apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      # Vincula esse deployment com um serviceAccount
      # namespace: prod
      serviceAccount: server
      containers:
      - name: server
        image: wesleywillians/hello-express
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
        ports:
        - containerPort: 3000