apiVersion: v1
kind: ServiceAccount
metadata:
  name: server

---

## RBAC - Role Based Access Control
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: server-read
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]

---


# Vincula um ServiceAccount com um binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: server-read-bind
subjects:
  - kind: ServiceAccount
    name: server
    namespace: dev
roleRef:
  kind: Role
  name: server-read
  apiGroup: rbac.authorization.k8s.io